from django.urls import path
from . import views
from . import admin_views
from . import report_views

urlpatterns = [
    path('', views.landing_view, name='landing'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('verify-otp/', views.verify_otp_view, name='verify_otp'),
    path('session-expired/', views.session_expired_notice_view, name='session_expired_notice'),
    path('forgot-password/', views.otp_forgot_password_view, name='otp_forgot_password'),
    path('reset-password/', views.otp_reset_password_view, name='otp_reset_password'),
    path('student/<int:student_id>/', views.student_profile_view, name='student_profile'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('profile/', views.profile_view, name='profile'),
    path('complete-profile/', views.complete_profile_view, name='complete_profile'),
    path('students/', views.students_list_view, name='students_list'),
    path('notifications/poll/', views.notifications_poll, name='notifications_poll'),
    path('session/heartbeat/', views.session_heartbeat_view, name='session_heartbeat'),

    # Admin URLs
    path('manage/users/', admin_views.admin_manage_users, name='admin_manage_users'),
    path('manage/create-user/', admin_views.admin_create_user, name='admin_create_user'),
    path('manage/user/<int:user_id>/delete/', admin_views.admin_delete_user, name='admin_delete_user'),
    path('manage/user/undo-delete/<str:token>/', admin_views.admin_undo_delete_user, name='admin_undo_delete_user'),
    path('manage/teachers/', admin_views.admin_teachers_list, name='admin_teachers_list'),
    path('manage/teacher/<int:teacher_id>/dashboard/', admin_views.admin_teacher_dashboard, name='admin_teacher_dashboard'),
    path('manage/create-class/', admin_views.admin_create_class, name='admin_create_class'),
    path('manage/enroll-student/', admin_views.admin_enroll_student, name='admin_enroll_student'),
    path('manage/cleanup-users/', admin_views.admin_cleanup_users, name='admin_cleanup_users'),
    path('manage/create-superuser/', admin_views.admin_create_superuser, name='admin_create_superuser'),
    path('manage/upload-students/', admin_views.admin_upload_students, name='admin_upload_students'),
    path('manage/registrations/<int:request_id>/approve/', admin_views.admin_approve_registration, name='admin_approve_registration'),
    path('manage/registrations/<int:request_id>/reject/', admin_views.admin_reject_registration, name='admin_reject_registration'),
    path('manage/registrations/undo-reject/<str:token>/', admin_views.admin_undo_reject_registration, name='admin_undo_reject_registration'),
    path('manage/approved-student/<int:student_id>/edit/', admin_views.admin_edit_approved_student, name='admin_edit_approved_student'),
    path('manage/approved-student/<int:student_id>/suspend/', admin_views.admin_suspend_approved_student, name='admin_suspend_approved_student'),
    path('manage/approved-student/undo-suspend/<str:token>/', admin_views.admin_undo_suspend_approved_student, name='admin_undo_suspend_approved_student'),
    path('manage/user/<int:user_id>/lift-suspension/', admin_views.admin_lift_messaging_suspension, name='admin_lift_messaging_suspension'),
    path('manage/user/undo-lift-suspension/<str:token>/', admin_views.admin_undo_lift_messaging_suspension, name='admin_undo_lift_messaging_suspension'),
    path('manage/all-classes/', admin_views.admin_all_classes, name='admin_all_classes'),
    path('manage/class/<int:class_id>/', admin_views.admin_view_class, name='admin_view_class'),
    path('manage/class/<int:class_id>/delete/', admin_views.admin_delete_class, name='admin_delete_class'),
    path('manage/class/undo-delete/<str:token>/', admin_views.admin_undo_delete_class, name='admin_undo_delete_class'),
    path('manage/audit-log/', admin_views.admin_audit_log, name='admin_audit_log'),
    path('manage/admins/', admin_views.admin_manage_admins, name='admin_manage_admins'),
    path('report/download/', report_views.download_report, name='download_report'),
]
