# Generated by Django 5.0 on 2026-02-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_alert_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnesscheckin',
            name='text_response',
            field=models.TextField(blank=True, help_text='Optional: How are you feeling today?', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('high_risk', 'High Risk Student'), ('missing_assignments', 'Missing Assignments'), ('low_attendance', 'Low Attendance'), ('wellness_concern', 'Wellness Concern'), ('teacher_concern', 'Teacher Concern'), ('emotional_distress', 'Emotional Distress')], max_length=30),
        ),
    ]
