# Generated by Django 5.0 on 2026-02-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0003_wellnesscheckin_text_response_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('high_risk', 'High Risk Student'), ('missing_assignments', 'Missing Assignments'), ('low_attendance', 'Low Attendance'), ('wellness_concern', 'Wellness Concern'), ('teacher_concern', 'Teacher Concern'), ('emotional_distress', 'Emotional Distress'), ('ai_intervention', 'AI Intervention Created')], max_length=30),
        ),
    ]
