# Generated by Django 5.0 on 2026-04-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0006_riskassessment_failing_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
