# Generated by Django 5.0 on 2026-02-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_of_birth_user_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_level',
            field=models.CharField(blank=True, choices=[('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10')], max_length=2, null=True),
        ),
    ]
