# Generated by Django 5.0 on 2026-02-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='id_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
