# Generated by Django 5.0 on 2026-03-09 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_existing_admins_as_superadmin(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='admin').update(admin_role='superadmin')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('registrar', 'Registrar'), ('data_viewer', 'Data Viewer')], max_length=20, null=True),
        ),
        migrations.RunPython(set_existing_admins_as_superadmin, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_DELETED', 'User Deleted'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('BULK_USER_CLEANUP', 'Bulk User Cleanup'), ('CSV_UPLOADED', 'CSV Uploaded'), ('STUDENT_REGISTERED', 'Student Registered'), ('CLASS_CREATED', 'Class Created'), ('CLASS_DELETED', 'Class Deleted'), ('CLASS_EDITED', 'Class Edited'), ('STUDENT_ENROLLED', 'Student Enrolled'), ('STUDENT_REMOVED_FROM_CLASS', 'Student Removed from Class'), ('ASSIGNMENT_CREATED', 'Assignment Created'), ('ASSIGNMENT_DELETED', 'Assignment Deleted'), ('SUBMISSION_GRADED', 'Submission Graded'), ('GRADE_CHANGED', 'Grade Changed'), ('CONCERN_SUBMITTED', 'Concern Submitted'), ('INTERVENTION_CREATED', 'Intervention Created'), ('INTERVENTION_UPDATED', 'Intervention Updated'), ('ALERT_RESOLVED', 'Alert Resolved'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('SUPERUSER_CREATED', 'Superuser Created'), ('REPORT_DOWNLOADED', 'Report Downloaded'), ('AI_USED', 'AI Assistant Used')], max_length=50)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor'], name='accounts_au_actor_i_4b63b5_idx'), models.Index(fields=['action'], name='accounts_au_action_5ca9a9_idx'), models.Index(fields=['timestamp'], name='accounts_au_timesta_276167_idx')],
            },
        ),
    ]
