# Generated by Django 5.0 on 2026-02-28 05:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_attachment_alter_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\Campus Care_Project\\campus-care-project\\media'), upload_to='message_attachments/'),
        ),
    ]
