# Generated by Django 5.0 on 2026-02-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_class_section_alter_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='year_level',
            field=models.CharField(blank=True, choices=[('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10')], max_length=2, null=True),
        ),
    ]
