# Generated by Django 5.0 on 2026-04-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_assignment_allow_late_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of times a student can submit this assignment.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempts_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
