# Generated by Django 5.0 on 2026-04-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_assignment_max_attempts_submission_attempts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='available_at',
            field=models.DateTimeField(blank=True, help_text='Date and time the assignment becomes available for submission.', null=True),
        ),
    ]
